### ISSUE TITLE
Purple Screen and Freezing on Apple TV 1st Gen

### ISSUE THREAD

**Issue by richdroid** [Protocol-X/script.video.funimationnow#3]
Running Kodi 15.2 on my 1st gen Apple TV and when I start up the Funimation add-on I am taken to a blank purple screen with a search icon in the corner (see attached picture) I also, am unable to exit this screen unless I force a reboot. 
![img_20170117_194049989](https://cloud.githubusercontent.com/assets/25188750/22046784/16d6a19c-dcf1-11e6-912d-f35f2d504d6f.jpg)

**Comment by Protocol-X** [comment]
Ok, yeah this will not work on 15 by default.  A friend had to do some hack work to make it work. 

What were you using before this?  You said this fixed an issue

**Comment by Protocol-X** [comment]
How did you find this btw?  It is not even in the repo yet and I haven't posted links.

**Comment by richdroid** [comment]
@Protocol-X I was using the older add-on until yesterday when I started getting a message about a local network error when I tried to play a video. And I found this when I searched "Funimation Kodi Add-on issue" or something like that.

**Comment by Protocol-X** [comment]
Ah looks like the shut down the old api today.  If you can get me a log file I can see about trying to get 15 support built in

**Comment by richdroid** [comment]
@Protocol-X Thanks so much! How do you get a log file tho?

**Comment by Protocol-X** [comment]
@richdroid try this http://kodi.wiki/view/Log_file/Easy

**Comment by richdroid** [comment]
@Protocol-X I tried to get a log file but, it seems the Kodi Log Uploader app is broken

**Comment by Protocol-X** [comment]
You can try this. http://forum.kodi.tv/showthread.php?tid=294643

By default the Web interface should be your tv ip and the port 8888. You can check in the settings

**Comment by richdroid** [comment]
@Protocol-X I tried everything to try to extract the log file but, in the end I couldn't do it. So, I attached a couple of photos of semi relevant parts that relate to the add-on in the log. 
![img_20170117_222739432](https://cloud.githubusercontent.com/assets/25188750/22049957/e1b6ed64-dd04-11e6-9666-7babe171196f.jpg)

**Comment by Protocol-X** [comment]
You have the wrong file downloaded it seems.  Should not day -master

**Comment by richdroid** [comment]
@Protocol-X Ohhhhhh now I feel like an idiot, sorry for wasting your time. Could you give me a link to download the correct file please? Thanks for everything Protocol-X!

**Comment by Protocol-X** [comment]
Try removing the -master from the zip name and the folder inside the zip

**Comment by Protocol-X** [comment]
Just extract it , rename the folder, then zip it again.   Should work.

**Comment by Protocol-X** [comment]
When it is on github it adds the extra path, I dont have it accepted on the repo yet so I dont have a download link other than the one on github

**Comment by Protocol-X** [comment]
If you still can't get it working, I can email you a copy if you provide
your email.   And it is not a waste of my time.  You can't help github
changed the format

**Comment by richdroid** [comment]
@Protocol-X I was unable to get it working properly, so my email is rhendrafamily@gmail.com

**Comment by Protocol-X** [comment]
Thanks,  I will create an export for you after I return from work this
evening.
